apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# kustomize doesn't work with rollouts, so I'm using deployments

  #- manifests/analysistemplate.yaml
  #- pg-backup.yaml
  #- manifests/secret.yaml
  #- manifests/todo-app-rollout.yaml
  #- manifests/todo-backend-rollout.yaml
resources:
- cronjob.yaml
- ingress.yaml
- postgres-service.yaml
- pv.yaml
- pvc.yaml
- statefulset.yaml
- todo-app-dep.yaml
- todo-app-svc.yaml
- todo-backend-dep.yaml
- todo-backend-svc.yaml
- broadcaster-dep.yaml
images:
- name: PROJECT/APP_IMAGE
  newName: pyrynot/todo-app
  newTag: 5e7d2c5a81abedd91455f1e476c10955101ee789
- name: PROJECT/BACKEND_IMAGE
  newName: pyrynot/todo-backend
  newTag: 5e7d2c5a81abedd91455f1e476c10955101ee789
- name: PROJECT/BACKUP_IMAGE
  newName: pyrynot/pg-backup:4.08
- name: PROJECT/BROADCASTER_IMAGE
  newName: pyrynot/broadcaster
  newTag: 5e7d2c5a81abedd91455f1e476c10955101ee789
- name: PROJECT/CRON_IMAGE
  newName: pyrynot/random-todo-generator
  newTag: 5e7d2c5a81abedd91455f1e476c10955101ee789
