apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: staging
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: PROJECT/BACKEND_IMAGE
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8000"
            - name: NATS_URL
              value: nats://my-nats:4222
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "263Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10


      #     volumeMounts:
      #       - name: image-cache
      #         mountPath: /app/static
      # volumes:
      #   - name: image-cache
      #     persistentVolumeClaim:
      #       claimName: image-cache-pvc
