apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
  namespace: project-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
      - name: broadcaster
        image: PROJECT/BROADCASTER_IMAGE
        imagePullPolicy: Always
        env:
        - name: NATS_URL
          value: nats://my-nats:4222
        - name: DISCORD_WEBHOOK_URL

          valueFrom:
            secretKeyRef:
                  name: discord-secret
                  key: DISCORD_WEBHOOK_URL
        resources:
            requests:
              memory: "129Mi"
              cpu: "100m"
            limits:
              memory: "263Mi"
              cpu: "201m"