apiVersion: v1
kind: Pod
metadata:
  name: wikipedia-pod
spec:

  initContainers:
  - name: init-wikipedia
    image: curlimages/curl:latest
    command: ["sh", "-c"]
    args:
      - curl -o /usr/share/nginx/html/index.html https://en.wikipedia.org/wiki/Kubernetes;
    volumeMounts:
    - name: www-data
      mountPath: /usr/share/nginx/html

  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: www-data
      mountPath: /usr/share/nginx/html

  - name: sidecar-random-wikipedia
    image: curlimages/curl:latest
    command: ["sh", "-c"]
    args:
      - |
        sleep $(( ( RANDOM % 600 )  + 300 ));
        curl -L -o /usr/share/nginx/html/index.html https://en.wikipedia.org/wiki/Special:Random;
    volumeMounts:
    - name: www-data
      mountPath: /usr/share/nginx/html

  volumes:
  - name: www-data
    emptyDir: {}