apiVersion: batch/v1
kind: CronJob
metadata:
  name: pg-backup-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pg-backup
            image: PROJECT/BACKUP_IMAGE
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/gcs/key.json"
            volumeMounts:
            - name: gcs-credentials
              mountPath: "/secrets/gcs"
            - name: database-sql
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: gcs-credentials
            secret:
              secretName: gcs-credentials
          - name: database-sql
            emptyDir: {}
