apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-cache-pvc # name of ther volume claim, this will be used in the deployment
  namespace: project-namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
      