apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage
  namespace: project-namespace
spec:
  metrics:
    - name: cpu-usage
      initialDelay: 10s
      interval: 60s
      count: 10
      successCondition: result[0] <= 0.000000000000005
      failureCondition: result[0] > 0.0000000000000005
      provider:
        prometheus:
          address: http://kube-prometheus-stack-1722-prometheus.prometheus.svc.cluster.local:9090
          query: |
            sum(rate(container_cpu_usage_seconds_total{namespace="project-namespace"}[1m])) by (namespace)
