FROM python:3.12.4-alpine3.19 AS build

WORKDIR /app

COPY reqs.txt /app/reqs.txt

RUN pip install --no-cache-dir --upgrade -r /app/reqs.txt

RUN pip install psycopg2-binary sqlalchemy

FROM python:3.12.4-alpine3.19

WORKDIR /app

COPY --from=build /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=build /usr/local/bin /usr/local/bin

COPY /backend/ /app/

ENV PYTHONUNBUFFERED=1

CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port ${PORT}"]