apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: todo-backend
    spec:
      containers:
      - env:
        - name: PORT
          value: "8000"
        - name: NATS_URL
          value: nats://my-nats:4222
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: postgres-secret
        image: PROJECT/BACKEND_IMAGE
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 20
        name: todo-backend
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 263Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
