apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: prometheus
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      url: http://loki.loki-stack:3100
      access: proxy
      isDefault: true
