---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummysite-controller
  namespace: project-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dummysite-controller
  namespace: project-namespace
rules:
- apiGroups: [""]
  resources: ["configmaps", "pods", "services", "events"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["example.com"]
  resources: ["dummysites"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dummysite-controller
subjects:
- kind: ServiceAccount
  name: dummysite-controller
  namespace: project-namespace
roleRef:
  kind: ClusterRole
  name: dummysite-controller
  apiGroup: rbac.authorization.k8s.io